name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: telegramdesktop/winget-releaser@latest
        with:
          identifier: Telegram.TelegramDesktop
          token: ${{ secrets.WINGET_TOKEN }}
